name: Build gdbserver

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  GDB_VERSION: "17.1"
  ICONV_VERSION: "1.18"
  GMP_VERSION: "6.3.0"
  MPFR_VERSION: "4.2.2"

jobs:
  build:
    name: gdbserver (${{ matrix.architecture  }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture: x86_64
            configure_host: "x86_64-linux-musl"
            cross_compile_packages: "x86_64-linux-musl-native"
            cc: x86_64-linux-musl-gcc
            cxx: x86_64-linux-musl-g++
            ar: x86_64-linux-musl-gcc-ar

          - architecture: armv7l
            configure_host: "arm-linux-musleabihf"
            cross_compile_packages: "armv7r-linux-musleabihf-cross"
            cc: armv7r-linux-musleabihf-gcc
            cxx: armv7r-linux-musleabihf-g++
            ar: armv7r-linux-musleabihf-gcc-ar

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Setup musl ToolChain
      run: |
        tar -xf $GITHUB_WORKSPACE/${{ matrix.cross_compile_packages }}.tgz

        echo "$GITHUB_WORKSPACE/${{ matrix.cross_compile_packages }}/bin" >> "$GITHUB_PATH"

        echo "CC=${{ matrix.cc }}" >> "$GITHUB_ENV"
        echo "CXX=${{ matrix.cxx }}" >> "$GITHUB_ENV"
        echo "AR=${{ matrix.ar }}" >> "$GITHUB_ENV"

    - name: Build libiconv from Source
      run: |
        wget https://ftp.gnu.org/gnu/libiconv/libiconv-${{ env.ICONV_VERSION }}.tar.gz
        tar -xf libiconv-${{ env.ICONV_VERSION }}.tar.gz
        cd libiconv-${{ env.ICONV_VERSION }}

        ./configure \
            --host=${{ matrix.configure_host }} \
            --enable-static \
            --prefix=$GITHUB_WORKSPACE/libiconv-${{ env.ICONV_VERSION }}/build
        make -j"$(nproc)"
        make install

    - name: Build GMP from Source
      run: |
        export PATH=$env:GITHUB_PATH
        wget https://ftp.gnu.org/gnu/gmp/gmp-${{ env.GMP_VERSION }}.tar.gz
        tar -xf gmp-${{ env.GMP_VERSION }}.tar.gz
        cd gmp-${{ env.GMP_VERSION }}

        ./configure \
            --host=${{ matrix.configure_host }} \
            --enable-static --disable-shared \
            --prefix=$GITHUB_WORKSPACE/gmp-${{ env.GMP_VERSION }}/build

        make -j"$(nproc)"
        make install

    - name: Build MPFR from Source
      run: |
        wget https://ftp.gnu.org/gnu/mpfr/mpfr-${{ env.MPFR_VERSION }}.tar.gz
        tar -xf mpfr-${{ env.MPFR_VERSION }}.tar.gz
        cd mpfr-${{ env.MPFR_VERSION }}

        ./configure \
            --host=${{ matrix.configure_host }} \
            --enable-static --disable-shared \
            --with-gmp=$GITHUB_WORKSPACE/gmp-${{ env.GMP_VERSION }}/build  \
            --prefix=$GITHUB_WORKSPACE/mpfr-${{ env.MPFR_VERSION }}/build
        make -j"$(nproc)"
        make install

    - name: Build gdbserver from Source
      run: |
        export CFLAGS="-Dc_ospeed=__c_ospeed -Dc_ispeed=__c_ispeed"
        export CXXFLAGS="-Dc_ospeed=__c_ospeed -Dc_ispeed=__c_ispeed"

        wget https://ftp.gnu.org/gnu/gdb/gdb-${{ env.GDB_VERSION }}.tar.gz
        tar -xf gdb-${{ env.GDB_VERSION }}.tar.gz
        cd gdb-${{ env.GDB_VERSION }}

        ./configure \
          --host=${{ matrix.configure_host }} \
          --enable-static --with-static-standard-libraries --disable-tui --disable-inprocess-agent \
          --with-libiconv=$GITHUB_WORKSPACE/libiconv-${{ env.ICONV_VERSION }}/build \
          --with-gmp=$GITHUB_WORKSPACE/gmp-${{ env.GMP_VERSION }}/build  \
          --with-mpfr=$GITHUB_WORKSPACE/mpfr-${{ env.MPFR_VERSION }}/build \
          --prefix=$GITHUB_WORKSPACE/gdb-${{ env.GDB_VERSION }}/build
        make LDFLAGS="-static" -j"$(nproc)"
        make install-strip

    - name: Verify Binary
      run: |
        echo "Checking built artifacts:"
        
        ls -la $GITHUB_WORKSPACE/gdb-${{ env.GDB_VERSION }}/build/bin
        
        file $GITHUB_WORKSPACE/gdb-${{ env.GDB_VERSION }}/build/bin/gdbserver

    - name: Upload gdbserver Artifact
      uses: actions/upload-artifact@v4
      with:
        name: gdbserver-${{ env.GDB_VERSION }}-linux-${{ matrix.architecture }}
        path: ${{ github.workspace }}/gdb-${{ env.GDB_VERSION }}/build/bin